/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: [
  //       {
  //         type: 'category',
  //         label: 'Tutorial Basics',
  //         items: ['tutorial-basics/congratulations', 'tutorial-basics/create-a-blog-post', 'tutorial-basics/create-a-document', 'tutorial-basics/create-a-page', 'tutorial-basics/deploy-your-site', 'gm'],
  //       },
  //       {
  //         type: 'category',
  //         label: 'Tutorial Extras',
  //         items: ['tutorial-extras/manage-docs-versions', 'tutorial-extras/translate-your-site'],
  //       }
  //     ],
  //   }
  // ],
};




